#!/bin/sh

#
# jupyter
#
/usr/bin/invoke_app "$@" -t llm4code \
                         -C "start_jupyter -T @tool -t claude-demo.ipynb" \
                         -u anaconda-7 \
                         -w headless \
                         -r none
